# Site settings
title: JekeyllğŸ’»Hyde
description: 'ä¸“å¿ƒè‡´å¿—ææŠ€æœ¯<br>è®¤è®¤çœŸçœŸè€æµæ°“'
url: 'http://jekyllhy.de' 
baseurl: '/'
# google_analytics: 'UA-73116272-1'

author:
  name: 'JekyllHy.de'
  email: muyoshiki@hotmail.com
  twitter_username: hamasupo
  github_username:  sakiyomu
  linkedin_username:  shusept

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: [jekyll-paginate]

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']